[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "0.20.0" }

[package.metadata.risc0]
methods = ["check-odd", "check-even", "check-adult"]
