[package]
name = "check_adult"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.20.0", default-features = false, features = [ "std" ] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
